---
title: "Pull Foundry API"
author: "Geneviev Roberts"
date: "Created July 13, 2025 \nLast opened: `r format(Sys.Date(), '%B %d, %Y')`"
output: 
  html_notebook:
    toc: yes
---

# Overview 

Foundry API Documentation is [here](https://viascientific.github.io/vfdocs/ViaFoundry/api/)

```{r load_pkgs, include=TRUE}
library(dplyr)
library(stringr)
library(lubridate)
library(purrr)
library(tidyr)
library(ggplot2)
library(forcats)
library(tibble)
library(httr)
library(jsonlite)
library(mixtools)
library(effects)
library(pROC)
library(here)
```

```{r set_credentials, include=FALSE}
#load API credentials from file
source(here::here("credentials.R"))

#load constants
source(here::here("constants.R"))

#load querying functions
source(here::here("query_functions.R"))

#load survey cleaning functions
source(here::here("surveys", "survey_functions.R"))
```

```{r initiate foundry seesion, include=FALSE}
token <- init_foundry_session(email=email,
                     password=password,
                     access_url = access_url)
```

```{r last_updated_pt, include=FALSE}
last_updated_fdry <- get_time_fountry_last_updated(formatted=FALSE)
last_updated_fdry_fmt <- get_time_fountry_last_updated(formatted = TRUE)
print(last_updated_fdry_fmt)
```

```{r load_pts, include=FALSE}
#pull from the API
patients_raw <- get_df(foundry_token=token,
             access_url_base=access_url_base,
             api_url=patients_url)

#clean the patients dataframe
patients_all <- clean_patients_data(patients_raw)

# all patients who haven't withdrew
patients_clean <- patients_all %>%
  filter(studyendreason %in% c("", NA))
```

```{r load_surveys_new, include=FALSE}
#pull from the API
surveys_raw <- get_df(foundry_token=token,
             access_url_base=access_url_base,
             api_url=surveys_url)

surveys_clean <- clean_surveys_data(surveys_raw = surveys_raw,
                                    patients_clean = patients_clean)

# init. last updated timestamp for surveys
last_updated_surveys <- surveys_clean %>% pull(recorded_dttm) %>% max()
last_updated_surveys_fmt <- str_c("Last updated:", last_updated_surveys, current_tz, sep = " ")
```

## Summary of Enrollment
```{r compute enrollment}
enroll_summary_stats <- make_summary_enrollment_table(patients_all = patients_all,
                                                      patients_clean = patients_clean,
                                                      last_updated_fdry = last_updated_fdry)

enroll_summary_stats
```

